### ISSUE TITLE
Additional Travel Notes?

### ISSUE THREAD

**Issue by jacqio** [Dathwada/handynotes-travelguide#5]
Hello - I was interested in adding some other info to the mod. I've added raids, dungeons and flightpaths for BCC Classic as it was already extensible. If you're interested please see my fork. Note that most of the points on the world map are rough estimates. This only required a few tweaks to your existing code (handler.lua, constants.lua, config.lug, the locales and of course to DB.lua in large part) and digging into WoW's interface files/finding the right uids for the new maps. If it's too much trouble I can always just create a new mod instead. Please let me know for thought.

**Comment by Dathwada** [comment]
Hey - I haven't added more because there are already existing HandyNote plugins for [Dungeons + Raids](https://www.curseforge.com/wow/addons/handynotes_dungeonlocations-classic) (works for BCC too) and [Flightmasters](https://www.curseforge.com/wow/addons/handynotes_flightmasters-classic) (bcc version is pending) with additional functions rather than only show the locations on the map.

**Comment by jacqio** [comment]
Looks like neither are updated for TBC Classic or showing up in CurseForge yet - but if they're going to update then I guess that's good enough for the community and I'll just use my updates until they're ready. Thanks!
